version: '3'

services:
  database:
    image: mysql:5.7
    container_name: cat-mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=cat
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
  cat:
    image: rrtxdockerhub.com:5000/cat
    container_name: cat
    depends_on:
      - database
    ports:
      - 8089:8080
      - 2280:2280
    environment:
      # if you have your own mysql, config it here, and disable the 'mysql' config blow
      - MYSQL_URL=cat-mysql # links will maintain /etc/hosts, just use 'container_name'
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=root
      - MYSQL_PASSWD=
      - MYSQL_SCHEMA=cat

